In [67]:
import numpy as np
import pandas as pd

In [68]:
Train_data = pd.read_csv("nsl-kdd/KDDTrain+_20Percent.txt", header=None)
Test_data = pd.read_csv("nsl-kdd/KDDTest+.txt", header=None)
Test_data.head()

,0,1,2,3,4,5,6,7,8,9,...,33,34,35,36,37,38,39,40,41,42
0,0,tcp,private,REJ,0,0,0,0,0,0,...,0.04,0.06,0.00,0.00,0.0,0.0,1.00,1.00,neptune,21
1,0,tcp,private,REJ,0,0,0,0,0,0,...,0.00,0.06,0.00,0.00,0.0,0.0,1.00,1.00,neptune,21
2,2,tcp,ftp_data,SF,12983,0,0,0,0,0,...,0.61,0.04,0.61,0.02,0.0,0.0,0.00,0.00,normal,21
3,0,icmp,eco_i,SF,20,0,0,0,0,0,...,1.00,0.00,1.00,0.28,0.0,0.0,0.00,0.00,saint,15
4,1,tcp,telnet,RSTO,0,15,0,0,0,0,...,0.31,0.17,0.03,0.02,0.0,0.0,0.83,0.71,mscan,11

In [69]:
for idx in range(43):
    print(len(np.sort(Train_data[idx].unique())))
    print(np.sort(Train_data[idx].unique()))
    print("<----------------------END--------------------------->")

758
[    0     1     2     3     4     5     6     7     8     9    10    11
    12    13    14    15    16    17    18    19    20    21    22    23
    24    25    26    27    28    29    30    31    32    33    35    36
    37    38    39    40    41    42    43    45    46    50    53    55
    56    57    58    59    60    63    66    69    70    78    81    88
    89    92    96    98   101   102   103   107   113   116   119   121
   129   131   132   136   140   142   149   151   156   159   161   168
   169   171   179   190   191   192   198   202   207   210   222   232
   235   240   244   251   252   255   261   263   264   265   272   274
   275   276   279   282   284   294   297   299   310   315   318   322
   323   347   357   362   378   387   397   398   407   409   421   423
   430   432   450   454   461   465   475   479   500   507   524   525
   542   550   560   571   575   583   584   589   590   610   618   620
   638   639   642   666   667   682   687   694   708   710   718   727
   730   756   770   771   778   786   799   804   815   826   829   831
   842   853   854   860   871   887   891   905   914   915   918   931
   938   945  1031  1045  1049  1051  1079  1082  1096  1100  1125  1130
  1133  1185  1195  1198  1200  1208  1213  1228  1235  1278  1313  1327
  1334  1398  1464  1525  1530  1540  1574  1609  1700  1714  1721  1730
  1774  1839  1864  1896  1900  1979  1985  1990  2005  2009  2015  2029
  2035  2046  2052  2059  2099  2115  2130  2140  2165  2178  2207  2217
  2230  2269  2289  2333  2349  2355  2401  2414  2420  2448  2450  2467
  2474  2475  2511  2530  2532  2540  2550  2580  2584  2585  2586  2589
  2601  2603  2620  2629  2630  2638  2639  2641  2650  2670  2671  2705
  2708  2712  2713  2736  2775  2814  2835  2845  2910  2969  2976  2980
  3026  3030  3047  3049  3083  3106  3143  3209  3296  3301  3355  3405
  3409  3447  3469  3487  3584  3660  3690  3735  3764  3779  3795  3916
  3924  3949  3977  3980  3983  3995  4021  4080  4115  4129  4134  4189
  4219  4224  4229  4263  4280  4298  4309  4329  4345  4374  4380  4382
  4400  4420  4468  4474  4530  4535  4545  4550  4576  4610  4629  4641
  4661  4675  4685  4701  4721  4764  4794  4814  4816  4834  4852  4931
  4961  4965  5036  5041  5042  5043  5044  5046  5048  5051  5055  5057
  5061  5062  5063  5065  5066  5080  5290  5300  5385  5410  5470  5607
  5632  5658  5682  5698  5749  5753  5775  5784  5831  5849  5915  5925
  5954  6064  6070  6071  6141  6143  6163  6192  6214  6284  6285  6349
  6372  6381  6515  6522  6531  6552  6565  6616  6707  6719  6892  6917
  7009  7025  7034  7070  7130  7158  7232  7247  7412  7580  7631  7701
  7755  7787  7790  7805  7850  7976  7999  8017  8035  8048  8122  8197
  8217  8220  8257  8337  8359  8397  8417  8437  8477  8486  8556  8610
  8621  8625  8649  8655  8675  8695  8795  8835  8895  8952  9002  9015
  9033  9052  9093  9094  9100  9114  9115  9195  9219  9235  9257  9305
  9375  9431  9455  9505  9515  9535  9592  9645  9658  9725  9741  9801
  9838  9841  9899  9908 10009 10059 10103 10120 10249 10264 10326 10332
 10340 10349 10395 10455 10629 10656 10706 10774 10835 10946 11014 11338
 11371 11431 11457 11460 11481 11565 11854 12013 12039 12041 12044 12085
 12096 12123 12124 12160 12202 12278 12417 12571 12666 12683 12705 12743
 12753 12773 12774 12833 12892 12993 13113 13141 13288 13308 13335 13339
 13368 13417 13428 13430 13488 13500 13501 13535 13564 13663 13678 13805
 13816 13904 13918 13958 13967 13998 14101 14360 14380 14462 14517 14608
 14680 15122 15159 15168 15244 15435 15624 16513 16533 16553 16744 16754
 16800 16872 16885 16941 16965 17025 17038 17105 17233 17297 17365 17399
 17419 17784 17833 17903 17904 17944 17964 17998 18338 18418 18438 18521
 18888 19025 19759 20252 21023 21123 21223 21243 21263 21701 21747 21767
 21846 21866 21927 21967 22336 22536 22556 22741 22821 22841 22861 23120
 25420 25641 25701 25910 25950 25990 26070 26090 26525 26588 26628 26768
 26848 26983 27018 27241 27401 27421 27481 27720 29053 30057 30217 30337
 30418 30438 30679 31118 31301 31401 31421 31461 31581 31601 31729 31809
 31829 31849 31905 32038 32244 32284 35240 35682 36131 36151 36280 36429
 36613 36653 36700 36741 36918 36965 37007 37072 37370 37498 37668 37688
 37728 37749 37815 37847 37874 37912 38192 38214 38314 38384 38404 38426
 38657 38776 38818 38977 39103 39313 39399 39438 39507 39602 39627 39667
 39804 39910 40025 40053 40142 40171 40295 40403 40423 40703 40806 41111
 41218 41254 41285 41307 41476 41541 41561 41802 42021 42260 42470 42636
 42658 42862]
<----------------------END--------------------------->
3
['icmp' 'tcp' 'udp']
<----------------------END--------------------------->
66
['IRC' 'X11' 'Z39_50' 'auth' 'bgp' 'courier' 'csnet_ns' 'ctf' 'daytime'
 'discard' 'domain' 'domain_u' 'echo' 'eco_i' 'ecr_i' 'efs' 'exec'
 'finger' 'ftp' 'ftp_data' 'gopher' 'hostnames' 'http' 'http_443'
 'http_8001' 'imap4' 'iso_tsap' 'klogin' 'kshell' 'ldap' 'link' 'login'
 'mtp' 'name' 'netbios_dgm' 'netbios_ns' 'netbios_ssn' 'netstat' 'nnsp'
 'nntp' 'ntp_u' 'other' 'pm_dump' 'pop_2' 'pop_3' 'printer' 'private'
 'red_i' 'remote_job' 'rje' 'shell' 'smtp' 'sql_net' 'ssh' 'sunrpc'
 'supdup' 'systat' 'telnet' 'tim_i' 'time' 'urh_i' 'urp_i' 'uucp'
 'uucp_path' 'vmnet' 'whois']
<----------------------END--------------------------->
11
['OTH' 'REJ' 'RSTO' 'RSTOS0' 'RSTR' 'S0' 'S1' 'S2' 'S3' 'SF' 'SH']
<----------------------END--------------------------->
1665
[        0         1         4 ...   7248552   7665876 381709090]
<----------------------END--------------------------->
3922
[      0       1       4 ... 5150772 5150836 5151385]
<----------------------END--------------------------->
2
[0 1]
<----------------------END--------------------------->
3
[0 1 3]
<----------------------END--------------------------->
2
[0 1]
<----------------------END--------------------------->
22
[ 0  1  2  3  4  5  6  7 11 12 14 15 17 18 19 20 22 24 25 28 30 77]
<----------------------END--------------------------->
5
[0 1 2 3 4]
<----------------------END--------------------------->
2
[0 1]
<----------------------END--------------------------->
28
[  0   1   2   3   4   5   6   7   9  12  13  19  31  38  83 107 110 151
 157 193 217 371 457 462 520 558 789 884]
<----------------------END--------------------------->
2
[0 1]
<----------------------END--------------------------->
3
[0 1 2]
<----------------------END--------------------------->
28
[  0   1   2   3   4   5   6   7   9  10  14  38  54  91 100 121 146 151
 179 191 247 417 508 512 572 629 867 975]
<----------------------END--------------------------->
20
[ 0  1  2  3  4  5  6  8 11 13 14 15 17 18 19 20 21 29 38 40]
<----------------------END--------------------------->
2
[0 1]
<----------------------END--------------------------->
7
[0 1 2 3 4 5 8]
<----------------------END--------------------------->
1
[0]
<----------------------END--------------------------->
1
[0]
<----------------------END--------------------------->
2
[0 1]
<----------------------END--------------------------->
466
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252
 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270
 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288
 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306
 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324
 325 326 327 328 329 330 333 334 335 336 337 338 340 341 342 344 346 347
 348 350 351 352 353 354 355 356 357 358 360 361 362 363 364 365 366 367
 368 370 373 375 376 378 379 380 381 382 383 384 388 389 390 391 393 394
 397 398 399 401 402 403 404 405 406 407 408 409 410 411 413 417 418 419
 421 422 423 424 425 427 432 433 434 435 436 437 438 439 440 441 442 444
 445 446 447 448 449 450 451 452 453 454 456 457 458 459 460 461 463 464
 467 468 470 471 472 473 476 477 478 479 480 481 482 484 485 486 487 488
 489 490 491 492 493 494 496 497 500 502 506 507 508 509 510 511]
<----------------------END--------------------------->
414
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 101 102 103 104 105 106 107 108 109
 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127
 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145
 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163
 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181
 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199
 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217
 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235
 236 237 238 239 240 242 243 244 245 246 247 248 249 250 251 252 253 254
 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272
 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289 290
 291 292 293 295 296 297 299 300 301 302 303 304 305 306 307 308 309 310
 311 312 313 314 315 316 317 318 319 321 322 323 325 326 327 335 337 338
 340 344 348 350 351 352 353 354 355 356 358 361 362 363 364 365 367 373
 375 376 378 379 380 381 384 390 391 397 398 399 401 402 403 406 407 408
 417 419 423 427 434 435 436 437 438 439 440 441 442 444 445 446 447 449
 450 451 452 453 454 456 457 458 459 460 461 464 467 468 471 473 476 477
 478 480 481 482 484 485 486 487 488 489 492 496 497 500 508 509 510 511]
<----------------------END--------------------------->
70
[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.33
 0.36 0.4  0.44 0.5  0.52 0.55 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66
 0.67 0.68 0.69 0.7  0.71 0.72 0.73 0.74 0.75 0.77 0.78 0.79 0.81 0.83
 0.85 0.86 0.88 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]
<----------------------END--------------------------->
56
[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.17 0.18 0.2  0.22 0.25 0.26 0.29 0.33 0.34 0.36 0.39 0.4
 0.41 0.43 0.45 0.46 0.5  0.53 0.55 0.57 0.59 0.6  0.65 0.67 0.74 0.75
 0.76 0.78 0.8  0.83 0.86 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 1.  ]
<----------------------END--------------------------->
72
[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.12 0.14 0.17
 0.19 0.2  0.21 0.22 0.23 0.25 0.26 0.27 0.29 0.3  0.31 0.32 0.33 0.34
 0.35 0.36 0.37 0.38 0.4  0.43 0.44 0.5  0.56 0.57 0.6  0.62 0.64 0.67
 0.69 0.71 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83 0.84
 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98
 0.99 1.  ]
<----------------------END--------------------------->
42
[0.   0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.14 0.15
 0.17 0.2  0.25 0.29 0.33 0.38 0.4  0.43 0.5  0.56 0.57 0.6  0.62 0.64
 0.67 0.69 0.71 0.73 0.74 0.75 0.76 0.79 0.8  0.81 0.83 0.84 0.85 1.  ]
<----------------------END--------------------------->
97
[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.67 0.69 0.7  0.71
 0.72 0.73 0.74 0.75 0.77 0.78 0.79 0.8  0.81 0.82 0.83 0.85 0.86 0.87
 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]
<----------------------END--------------------------->
79
[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.35 0.36 0.37 0.38 0.39 0.4  0.41 0.42
 0.43 0.44 0.45 0.46 0.5  0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59
 0.6  0.61 0.62 0.63 0.64 0.67 0.69 0.7  0.73 0.75 0.76 0.77 0.78 0.79
 0.8  0.82 0.83 0.95 0.96 0.97 0.98 0.99 1.  ]
<----------------------END--------------------------->
57
[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.35 0.36 0.37 0.38 0.4  0.42 0.43 0.44
 0.45 0.47 0.5  0.55 0.56 0.57 0.6  0.62 0.67 0.71 0.75 0.8  0.83 0.88
 1.  ]
<----------------------END--------------------------->
256
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255]
<----------------------END--------------------------->
256
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255]
<----------------------END--------------------------->
101
[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.  ]
<----------------------END--------------------------->
101
[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.  ]
<----------------------END--------------------------->
101
[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.  ]
<----------------------END--------------------------->
63
[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.42
 0.43 0.44 0.45 0.46 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55 0.56 0.57
 0.6  0.67 0.75 0.8  0.86 0.97 1.  ]
<----------------------END--------------------------->
100
[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.39 0.4  0.41 0.42
 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55 0.56
 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7
 0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83 0.84
 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98
 0.99 1.  ]
<----------------------END--------------------------->
88
[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.22 0.23 0.24 0.25 0.26 0.27 0.28
 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41 0.42
 0.44 0.45 0.48 0.49 0.5  0.55 0.56 0.57 0.59 0.6  0.61 0.62 0.65 0.66
 0.67 0.69 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81
 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95
 0.96 0.97 0.98 1.  ]
<----------------------END--------------------------->
101
[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.  ]
<----------------------END--------------------------->
100
[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.24 0.25 0.26 0.27 0.28
 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41 0.42
 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55 0.56
 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7
 0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83 0.84

In [70]:
X_train = Train_data.iloc[:, 0:41]
Y_train = Train_data.iloc[:, 41]
difficulty = Train_data.iloc[:, 42]

X_test = Test_data.iloc[:, 0:41]
Y_test = Test_data.iloc[:, 41]
difficulty = Test_data.iloc[:, 42]

In [71]:
Y_train.value_counts(normalize=True)*100

41
normal             53.385996
neptune            32.875516
ipsweep             2.818355
satan               2.742934
portsweep           2.330105
smurf               2.099873
nmap                1.194824
back                0.778025
teardrop            0.746269
warezclient         0.718482
pod                 0.150842
guess_passwd        0.039695
warezmaster         0.027787
buffer_overflow     0.023817
imap                0.019848
rootkit             0.015878
multihop            0.007939
phf                 0.007939
ftp_write           0.003970
land                0.003970
loadmodule          0.003970
spy                 0.003970
Name: proportion, dtype: float64

In [73]:
cat_cols = [1, 2, 3]
#BOTH TRAIN AND TEST DATA SHOULD BE ONE-HOT-ENCODED TOGETHER
combined = pd.concat([X_train, X_test], axis = 0)
combined = pd.get_dummies(combined,columns = cat_cols, dtype=int)

print(combined.shape)
X_train = combined.iloc[:len(X_train), :]
X_test = combined.iloc[len(X_train):, :]

(47736, 119)

In [74]:
X_train.head()

,0,4,5,6,7,8,9,10,11,12,...,3_REJ,3_RSTO,3_RSTOS0,3_RSTR,3_S0,3_S1,3_S2,3_S3,3_SF,3_SH
0,0,491,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,146,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,0,232,8153,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
4,0,199,420,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0